name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:  
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [ '3.9', '3.10' ]
        
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Display Python version
        run: python --version
      - uses: FedericoCarboni/setup-ffmpeg@v1
        id: setup-ffmpeg
      - run: pip install -r requirements.txt
      - run: python -m unittest discover -s ./ -p '*.py'
      - run: pylint *.py
        shell: bash

